using System;
using System.Collections.Generic;
using System.Text;
using Fminusminus;
using Fminusminus.Optimizer;
using Fminusminus.Errors;

namespace Fminusminus.CodeGen
{
    /// <summary>
    /// Code Generator for F-- - Translates AST to target code
    /// Supports multiple backends: CIL (.NET), C, JavaScript, Python, F--
    /// </summary>
    public class CodeGenerator
    {
        public enum TargetPlatform
        {
            CIL,        // .NET Common Intermediate Language
            C,          // C language
            JavaScript, // JavaScript
            Python,     // Python
            Fminus      // F-- itself (for debugging)
        }

        public enum OptimizationLevel
        {
            O0, // No optimization
            O1, // Basic optimizations
            O2, // Aggressive optimizations
            O3  // Maximum optimizations
        }

        private readonly ProgramNode _ast;
        private readonly StringBuilder _output;
        private int _indentLevel;
        private readonly TargetPlatform _targetPlatform;
        private readonly OptimizationLevel _optLevel;
        
        private Dictionary<string, string> _variables = new();
        private HashSet<string> _declaredVariables = new(); // Track declared variables
        private int _tempVarCounter;
        private int _labelCounter;

        public CodeGenerator(ProgramNode ast, TargetPlatform target = TargetPlatform.CIL, OptimizationLevel opt = OptimizationLevel.O1)
        {
            _ast = ast;
            _output = new StringBuilder();
            _targetPlatform = target;
            _optLevel = opt;
        }

        public string Generate()
        {
            try
            {
                _output.Clear();
                _variables.Clear();
                _declaredVariables.Clear();
                
                // Apply optimizations if enabled
                var optimizedAst = _ast;
                if (_optLevel > OptimizationLevel.O0)
                {
                    var optimizer = new AstOptimizer(_optLevel);
                    optimizedAst = optimizer.Optimize(_ast);
                }

                // Generate header based on target platform
                GenerateHeader();

                // Generate code for the program
                GenerateProgram(optimizedAst);

                // Generate footer
                GenerateFooter();

                return _output.ToString();
            }
            catch (Exception ex)
            {
                throw new InvalidOperationException($"Code generation failed: {ex.Message}", ex);
            }
        }

        private void GenerateHeader()
        {
            switch (_targetPlatform)
            {
                case TargetPlatform.CIL:
                    _output.AppendLine(".assembly extern mscorlib { }");
                    _output.AppendLine(".assembly Fminus { }");
                    _output.AppendLine(".module Fminus.exe");
                    _output.AppendLine();
                    break;

                case TargetPlatform.C:
                    _output.AppendLine("#include <stdio.h>");
                    _output.AppendLine("#include <stdlib.h>");
                    _output.AppendLine("#include <string.h>");
                    _output.AppendLine();
                    break;

                case TargetPlatform.JavaScript:
                    _output.AppendLine("// F-- generated JavaScript");
                    _output.AppendLine("\"use strict\";");
                    _output.AppendLine();
                    break;

                case TargetPlatform.Python:
                    _output.AppendLine("# F-- generated Python");
                    _output.AppendLine("import sys");
                    _output.AppendLine();
                    break;

                case TargetPlatform.Fminus:
                    _output.AppendLine("// Generated by F-- Code Generator");
                    _output.AppendLine();
                    break;
            }
        }

        private void GenerateFooter()
        {
            switch (_targetPlatform)
            {
                case TargetPlatform.C:
                    _output.AppendLine("    return 0;");
                    _output.AppendLine("}");
                    break;

                case TargetPlatform.JavaScript:
                    _output.AppendLine("})();");
                    break;

                case TargetPlatform.Python:
                    _output.AppendLine("    sys.exit(main())");
                    _output.AppendLine();
                    _output.AppendLine("if __name__ == \"__main__\":");
                    _output.AppendLine("    main()");
                    break;

                case TargetPlatform.CIL:
                    _output.AppendLine("        ret");
                    _output.AppendLine("    }");
                    _output.AppendLine("}");
                    break;
            }
        }

        private void GenerateProgram(ProgramNode program)
        {
            switch (_targetPlatform)
            {
                case TargetPlatform.CIL:
                    GenerateCILProgram(program);
                    break;
                case TargetPlatform.C:
                    GenerateCProgram(program);
                    break;
                case TargetPlatform.JavaScript:
                    GenerateJavaScriptProgram(program);
                    break;
                case TargetPlatform.Python:
                    GeneratePythonProgram(program);
                    break;
                case TargetPlatform.Fminus:
                    GenerateFminusProgram(program);
                    break;
            }
        }

        #region CIL Code Generation
        private void GenerateCILProgram(ProgramNode program)
        {
            _output.AppendLine(".class private auto ansi Program");
            _output.AppendLine("{");
            _output.AppendLine("    .method static hidebysig void main() cil managed");
            _output.AppendLine("    {");
            _output.AppendLine("        .entrypoint");
            
            // Collect all variables first
            var locals = new List<string>();
            if (program.StartBlock != null)
            {
                foreach (var stmt in program.StartBlock.Statements)
                {
                    if (stmt is AssignmentNode assign)
                    {
                        string type = assign.Value is StringLiteralNode ? "string" : "int32";
                        locals.Add($"[0] {type} '{assign.VariableName}'");
                    }
                }
            }
            
            if (locals.Count > 0)
            {
                _output.AppendLine("        .locals init (");
                for (int i = 0; i < locals.Count; i++)
                {
                    _output.Append($"            {locals[i]}");
                    if (i < locals.Count - 1)
                        _output.AppendLine(",");
                    else
                        _output.AppendLine();
                }
                _output.AppendLine("        )");
            }
            
            _output.AppendLine("        .maxstack 16");

            if (program.StartBlock != null)
            {
                foreach (var stmt in program.StartBlock.Statements)
                {
                    GenerateCILStatement(stmt);
                }
            }

            _output.AppendLine("        ret");
            _output.AppendLine("    }");
            _output.AppendLine("}");
        }

        private void GenerateCILStatement(StatementNode stmt)
        {
            switch (stmt)
            {
                case PrintlnStatementNode println:
                    GenerateCILPrintln(println);
                    break;

                case PrintStatementNode print:
                    GenerateCILPrint(print);
                    break;
                    
                case ReturnStatementNode ret:
                    _output.AppendLine($"        ldc.i4 {ret.ReturnCode}");
                    _output.AppendLine("        ret");
                    break;

                case AssignmentNode assign:
                    GenerateCILAssignment(assign);
                    break;

                case MemoryStatementNode memory:
                    _output.AppendLine($"        ldstr \"{memory.Property}: 1024 MB\"");
                    _output.AppendLine("        call void [mscorlib]System.Console::WriteLine(string)");
                    break;
                    
                case EndStatementNode:
                    // End statement just returns 0 in CIL
                    _output.AppendLine("        ldc.i4 0");
                    _output.AppendLine("        ret");
                    break;
            }
        }
        
        private void GenerateCILPrintln(PrintlnStatementNode println)
        {
            if (println.Expression is StringLiteralNode str)
            {
                _output.AppendLine($"        ldstr \"{EscapeString(str.Value)}\"");
                _output.AppendLine("        call void [mscorlib]System.Console::WriteLine(string)");
            }
            else if (println.Expression is VariableNode var)
            {
                _output.AppendLine($"        ldloc '{var.Name}'");
                _output.AppendLine("        call void [mscorlib]System.Console::WriteLine(object)");
            }
            else if (println.Expression is NumberLiteralNode num)
            {
                _output.AppendLine($"        ldc.i4 {num.Value}");
                _output.AppendLine("        call void [mscorlib]System.Console::WriteLine(int32)");
            }
        }
        
        private void GenerateCILPrint(PrintStatementNode print)
        {
            if (print.Expression is StringLiteralNode str)
            {
                _output.AppendLine($"        ldstr \"{EscapeString(str.Value)}\"");
                _output.AppendLine("        call void [mscorlib]System.Console::Write(string)");
            }
            else if (print.Expression is NumberLiteralNode num)
            {
                _output.AppendLine($"        ldc.i4 {num.Value}");
                _output.AppendLine("        call void [mscorlib]System.Console::Write(int32)");
            }
        }
        
        private void GenerateCILAssignment(AssignmentNode assign)
        {
            if (assign.Value is StringLiteralNode strVal)
            {
                _output.AppendLine($"        ldstr \"{EscapeString(strVal.Value)}\"");
                _output.AppendLine($"        stloc '{assign.VariableName}'");
            }
            else if (assign.Value is NumberLiteralNode numVal)
            {
                _output.AppendLine($"        ldc.i4 {numVal.Value}");
                _output.AppendLine($"        stloc '{assign.VariableName}'");
            }
            else if (assign.Value is BooleanLiteralNode boolVal)
            {
                _output.AppendLine($"        ldc.i4 {(boolVal.Value ? 1 : 0)}");
                _output.AppendLine($"        stloc '{assign.VariableName}'");
            }
        }
        #endregion

        #region C Code Generation
        private void GenerateCProgram(ProgramNode program)
        {
            _output.AppendLine("int main() {");

            if (program.StartBlock != null)
            {
                foreach (var stmt in program.StartBlock.Statements)
                {
                    GenerateCStatement(stmt);
                }
            }

            _output.AppendLine("    return 0;");
            _output.AppendLine("}");
        }

        private void GenerateCStatement(StatementNode stmt)
        {
            switch (stmt)
            {
                case PrintlnStatementNode println:
                    GenerateCPrintln(println);
                    break;

                case PrintStatementNode print:
                    GenerateCPrint(print);
                    break;
                    
                case ReturnStatementNode ret:
                    _output.AppendLine($"    return {ret.ReturnCode};");
                    break;

                case AssignmentNode assign:
                    GenerateCAssignment(assign);
                    break;

                case MemoryStatementNode memory:
                    _output.AppendLine($"    printf(\"{memory.Property}: 1024 MB\\n\");");
                    break;
                    
                case EndStatementNode:
                    _output.AppendLine("    return 0;");
                    break;
            }
        }
        
        private void GenerateCPrintln(PrintlnStatementNode println)
        {
            if (println.Expression is StringLiteralNode str)
            {
                _output.AppendLine($"    printf(\"{EscapeString(str.Value)}\\n\");");
            }
            else if (println.Expression is VariableNode var)
            {
                _output.AppendLine($"    printf(\"%s\\n\", {var.Name});");
            }
            else if (println.Expression is NumberLiteralNode num)
            {
                _output.AppendLine($"    printf(\"%d\\n\", {num.Value});");
            }
        }
        
        private void GenerateCPrint(PrintStatementNode print)
        {
            if (print.Expression is StringLiteralNode str)
            {
                _output.AppendLine($"    printf(\"{EscapeString(str.Value)}\");");
            }
            else if (print.Expression is NumberLiteralNode num)
            {
                _output.AppendLine($"    printf(\"%d\", {num.Value});");
            }
        }
        
        private void GenerateCAssignment(AssignmentNode assign)
        {
            string varName = assign.VariableName;
            
            if (!_declaredVariables.Contains(varName))
            {
                _declaredVariables.Add(varName);
                
                if (assign.Value is StringLiteralNode strVal)
                {
                    _output.AppendLine($"    char* {varName} = \"{EscapeString(strVal.Value)}\";");
                }
                else if (assign.Value is NumberLiteralNode numVal)
                {
                    _output.AppendLine($"    int {varName} = {numVal.Value};");
                }
                else if (assign.Value is BooleanLiteralNode boolVal)
                {
                    _output.AppendLine($"    int {varName} = {(boolVal.Value ? 1 : 0)};");
                }
            }
            else
            {
                if (assign.Value is StringLiteralNode strVal)
                {
                    _output.AppendLine($"    {varName} = \"{EscapeString(strVal.Value)}\";");
                }
                else if (assign.Value is NumberLiteralNode numVal)
                {
                    _output.AppendLine($"    {varName} = {numVal.Value};");
                }
                else if (assign.Value is BooleanLiteralNode boolVal)
                {
                    _output.AppendLine($"    {varName} = {(boolVal.Value ? 1 : 0)};");
                }
            }
        }
        #endregion

        // ... (các regions khác tương tự)

        #region Helpers
        private string NewTempVar() => $"_t{_tempVarCounter++}";
        private string NewLabel() => $"L{_labelCounter++}";

        private void Indent()
        {
            _indentLevel++;
        }

        private void Dedent()
        {
            if (_indentLevel > 0) _indentLevel--;
        }

        private string GetIndent() => new string(' ', _indentLevel * 4);

        private string EscapeString(string input)
        {
            if (string.IsNullOrEmpty(input)) return "";
            
            StringBuilder sb = new();
            foreach (char c in input)
            {
                switch (c)
                {
                    case '\\': sb.Append("\\\\"); break;
                    case '\"': sb.Append("\\\""); break;
                    case '\n': sb.Append("\\n"); break;
                    case '\r': sb.Append("\\r"); break;
                    case '\t': sb.Append("\\t"); break;
                    case '\0': sb.Append("\\0"); break;
                    case '\b': sb.Append("\\b"); break;
                    case '\f': sb.Append("\\f"); break;
                    case '\v': sb.Append("\\v"); break;
                    default:
                        if (c < 32 || c > 127)
                            sb.Append($"\\u{(int)c:X4}");
                        else
                            sb.Append(c);
                        break;
                }
            }
            return sb.ToString();
        }
        #endregion
    }
}
